---
language: node_js
node_js:
- 0.1
env:
  global:
  - secure: ! 'Zh+1qJtlKdZ08l/xe39M2sYb4WZajqYYGgKRetSCSPjmflYRv7TD10X0Ah+qz2zcJrleeIZjLlNmQx8PoWzXZVZlMOcvCH+c06pZUR9hQFePHBDbHqBW9pGuBwGTpljO/xlCyZD/tF/RqoqyphYmIuwC6VCRdo4NgbCfvJYALF0='
  - secure: ! 'tSlZnWAdEd7UEjhTpXl1ypxtsG53n13fnv9YvVMh2qc2Hr04eYtZ3efFQsmBj25GTe7TYyOYB7oMY7JRn2gl/GyOy+D3911ADHdDBux0orQC9V64PK2XrxZomruaTjCDAPgPFp5ALW5Zo4MSFtf2GLOq+SBYYRlt5SLw6y1sqHY='
